I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 21, in script
    scene bg 2 at resize_to_1080p
  File "game/script.rpy", line 21, in <module>
    scene bg 2 at resize_to_1080p
NameError: name 'resize_to_1080p' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 21, in script
    scene bg 2 at resize_to_1080p
  File "D:\Renp\renpy-8.3.4-sdk\renpy\ast.py", line 1251, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\Renp\renpy-8.3.4-sdk\renpy\ast.py", line 1076, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "D:\Renp\renpy-8.3.4-sdk\renpy\ast.py", line 1076, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "D:\Renp\renpy-8.3.4-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Renp\renpy-8.3.4-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 21, in <module>
    scene bg 2 at resize_to_1080p
NameError: name 'resize_to_1080p' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
Rizal 1.0
Thu Dec 19 17:22:12 2024
